name: C Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker container with Ubuntu 16.04 (32-bit)
        run: docker pull i386/ubuntu:16.04

      - name: Build and run tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace i386/ubuntu:16.04 /bin/bash -c "
            apt-get update &&
            apt-get install -y gcc make diffutils git &&
            make clean &&
            make &&
            make test TEST_NAME=doubly_linked_list &&
            make test TEST_NAME=symbol &&
            make test TEST_NAME=commons &&
            ./assembler data

          "
